// Regenerates the product-card markup inside portfolio.html from
// data/products.json, in place, between the PRODUCTS:START/END markers.
//
// Run this any time data/products.json changes. It's also the reference
// implementation the drift check (check_portfolio_sync.mjs) uses to prove
// the checked-in HTML still matches the data file.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { renderBands } from "./portfolio_render.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DATA_PATH = join(ROOT, "data", "products.json");
const HTML_PATH = join(ROOT, "portfolio.html");

const START = "<!-- PRODUCTS:START (generated by scripts/build_portfolio.mjs from data/products.json — do not hand-edit between these markers) -->";
const END = "<!-- PRODUCTS:END -->";

function main() {
  const data = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  const generated = renderBands(data);
  const html = readFileSync(HTML_PATH, "utf8");

  const startIdx = html.indexOf(START);
  const endIdx = html.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    console.error("MISMATCH: could not find PRODUCTS:START/END markers in portfolio.html");
    process.exit(1);
  }

  const before = html.slice(0, startIdx + START.length);
  const after = html.slice(endIdx);
  const next = `${before}\n    ${generated}\n    ${after}`;

  writeFileSync(HTML_PATH, next, "utf8");
  console.log(`Wrote generated product cards into ${HTML_PATH}`);
}

main();
