// Regenerates hours-based pricing copy inside portfolio/bluemonster.html and
// pricing.html from data/pricing.json, in place, between the
// PRICING:START/END and CONSUMER_PRICING:START/END markers.
//
// Run this any time data/pricing.json changes (e.g. after the bluehelm
// config values change). It's also the reference implementation the drift
// check (check_pricing_sync.mjs) uses to prove the checked-in HTML still
// matches the data file. Same pattern as build_portfolio.mjs /
// check_portfolio_sync.mjs for the /portfolio page.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { renderBluemonsterPriceLine, renderConsumerPricingCards } from "./pricing_render.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DATA_PATH = join(ROOT, "data", "pricing.json");

const TARGETS = [
  {
    path: join(ROOT, "portfolio", "bluemonster.html"),
    start: "<!-- PRICING:START (generated by scripts/build_pricing.mjs from data/pricing.json — do not hand-edit between these markers) -->",
    end: "<!-- PRICING:END -->",
    render: renderBluemonsterPriceLine,
    inline: true, // no surrounding newline/indent — sits inside a one-line <div class="price">
  },
  {
    path: join(ROOT, "pricing.html"),
    start: "<!-- CONSUMER_PRICING:START (generated by scripts/build_pricing.mjs from data/pricing.json — do not hand-edit between these markers) -->",
    end: "<!-- CONSUMER_PRICING:END -->",
    render: renderConsumerPricingCards,
    inline: false,
  },
];

function main() {
  const data = JSON.parse(readFileSync(DATA_PATH, "utf8"));

  for (const target of TARGETS) {
    const html = readFileSync(target.path, "utf8");
    const startIdx = html.indexOf(target.start);
    const endIdx = html.indexOf(target.end);
    if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
      console.error(`MISMATCH: could not find markers in ${target.path}`);
      process.exit(1);
    }
    const generated = target.render(data);
    const before = html.slice(0, startIdx + target.start.length);
    const after = html.slice(endIdx);
    const next = target.inline
      ? `${before}${generated}${after}`
      : `${before}\n${generated}\n${after}`;
    writeFileSync(target.path, next, "utf8");
    console.log(`Wrote generated pricing copy into ${target.path}`);
  }
}

main();
