// Drift check (CLAUDE.md rule 17: verify by the artifact, never by an exit
// code or a printed checkmark). Two independent checks, both must pass:
//
// 1. INTRA-REPO: re-renders the pricing copy fresh from data/pricing.json
//    using the SAME render functions build_pricing.mjs uses, extracts what's
//    actually committed between the PRICING:START/END and
//    CONSUMER_PRICING:START/END markers in portfolio/bluemonster.html and
//    pricing.html, and fails loudly — printing the two strings it compared —
//    if they differ even by one character. This is the same pattern as
//    check_portfolio_sync.mjs for /portfolio.
//
// 2. CROSS-REPO: data/pricing.json claims to match specific fields in
//    mobluehq-platform's packages/bluehelm/src/bluehelm/config.py (the file
//    that actually bills the customer — see data/pricing.json's
//    "sourceOfTruth"). If a checkout of that repo can be found on this
//    machine, this script parses the four *_search_hours float defaults out
//    of config.py and FAILS if any of them differ from data/pricing.json.
//    If no checkout can be found, it prints a loud, unambiguous WARN (never
//    a silent pass) so a false green can't be mistaken for "checked."
//
// Usage: node scripts/check_pricing_sync.mjs [pathToBluehelmConfigPy]
import { readFileSync } from "node:fs";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { execFileSync } from "node:child_process";
import { renderBluemonsterPriceLine, renderConsumerPricingCards, tierById } from "./pricing_render.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DATA_PATH = join(ROOT, "data", "pricing.json");

let failed = false;

function fail(msg) {
  console.error(`MISMATCH: ${msg}`);
  failed = true;
}

function checkMarkerBlock(label, path, start, end, expected) {
  const html = readFileSync(path, "utf8");
  const startIdx = html.indexOf(start);
  const endIdx = html.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    fail(`could not find ${label} markers in ${path}`);
    return;
  }
  const actual = html.slice(startIdx + start.length, endIdx).trim();
  const expectedTrimmed = expected.trim();
  if (actual !== expectedTrimmed) {
    fail(`${label} in ${path} has drifted from data/pricing.json.`);
    console.error("Run `node scripts/build_pricing.mjs` and commit the result.");
    console.error(`--- expected (from data/pricing.json) ---\n${expectedTrimmed}`);
    console.error(`--- actual (currently committed) ---\n${actual}`);
    return;
  }
  console.log(`OK: ${label} in ${path} matches data/pricing.json.`);
}

// Candidate locations for the mobluehq-platform checkout, checked in order.
// This repo (mobluehq-site) and mobluehq-platform are separate repos with no
// package dependency between them, so there is no import-time way to read
// config.py directly — this is the best-effort filesystem probe the task
// asked for ("add a check script that FAILS when the page and the config
// disagree" — this is that script for the one case a static site CAN reach
// its cross-repo source of truth: a sibling checkout on the same machine).
function findConfigPy(explicitPath) {
  const candidates = [
    explicitPath,
    process.env.BLUEHELM_CONFIG_PY,
    join(ROOT, "..", "mobluehq-platform", "packages", "bluehelm", "src", "bluehelm", "config.py"),
  ].filter(Boolean);
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

function parseHoursField(text, fieldName) {
  // Matches e.g. `    entry_search_hours: float = 4.0` — the dataclass
  // field declaration with its default, not the CLI/env override lines.
  const re = new RegExp(`\\b${fieldName}\\s*:\\s*float\\s*=\\s*([0-9]+(?:\\.[0-9]+)?)`);
  const m = text.match(re);
  return m ? parseFloat(m[1]) : null;
}

function main() {
  const data = JSON.parse(readFileSync(DATA_PATH, "utf8"));

  // --- Check 1: intra-repo (JSON -> generated HTML) ---
  checkMarkerBlock(
    "PRICING block (bluemonster.html)",
    join(ROOT, "portfolio", "bluemonster.html"),
    "<!-- PRICING:START (generated by scripts/build_pricing.mjs from data/pricing.json — do not hand-edit between these markers) -->",
    "<!-- PRICING:END -->",
    renderBluemonsterPriceLine(data)
  );
  checkMarkerBlock(
    "CONSUMER_PRICING block (pricing.html)",
    join(ROOT, "pricing.html"),
    "<!-- CONSUMER_PRICING:START (generated by scripts/build_pricing.mjs from data/pricing.json — do not hand-edit between these markers) -->",
    "<!-- CONSUMER_PRICING:END -->",
    renderConsumerPricingCards(data)
  );

  // --- Check 2: cross-repo (JSON -> bluehelm/config.py) ---
  const explicitPath = process.argv[2];
  const configPath = findConfigPy(explicitPath);
  if (!configPath) {
    console.warn(
      "WARN: could not find a mobluehq-platform checkout's packages/bluehelm/src/bluehelm/config.py " +
        "on this machine (checked explicit arg, $BLUEHELM_CONFIG_PY, and a sibling ../mobluehq-platform). " +
        "The cross-repo check was NOT performed — this is a gap in coverage, not a pass. " +
        "Re-run with the path explicit, e.g.: node scripts/check_pricing_sync.mjs /path/to/mobluehq-platform/packages/bluehelm/src/bluehelm/config.py"
    );
  } else {
    let branchNote = "";
    try {
      const branch = execFileSync("git", ["-C", dirname(configPath), "rev-parse", "--abbrev-ref", "HEAD"], {
        encoding: "utf8",
      }).trim();
      branchNote = ` (checkout is on branch "${branch}")`;
    } catch (_e) {
      // best-effort only; a missing/foreign git binary must not fail the gate
    }
    console.log(`Cross-repo check: comparing against ${configPath}${branchNote}`);
    const configText = readFileSync(configPath, "utf8");
    for (const tier of data.tiers) {
      const configValue = parseHoursField(configText, tier.configKey);
      if (configValue === null) {
        fail(`could not find field "${tier.configKey}" in ${configPath}`);
        continue;
      }
      if (configValue !== tier.hours) {
        fail(
          `data/pricing.json tier "${tier.id}" says ${tier.hours} hours but ` +
            `${configPath}'s ${tier.configKey} default is ${configValue}.`
        );
        continue;
      }
      console.log(`OK: tier "${tier.id}" (${tier.configKey}) — data/pricing.json (${tier.hours}) matches ${configPath} (${configValue}).`);
    }
  }

  if (failed) {
    console.error("\nFAILED: pricing copy has drifted. See MISMATCH lines above.");
    process.exit(1);
  }
  console.log("\nOK: all pricing sync checks passed.");
}

main();
