// Drift check (CLAUDE.md rule 17: verify by the artifact, never by an exit
// code or a printed checkmark). This re-renders the product cards fresh
// from data/products.json using the SAME renderBands() function
// build_portfolio.mjs uses, extracts what's actually committed between the
// PRODUCTS:START/END markers in portfolio.html, and fails loudly — printing
// the two strings it compared — if they differ even by one character.
//
// Run: node scripts/check_portfolio_sync.mjs
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { renderBands } from "./portfolio_render.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const DATA_PATH = join(ROOT, "data", "products.json");
const HTML_PATH = join(ROOT, "portfolio.html");

const START = "<!-- PRODUCTS:START (generated by scripts/build_portfolio.mjs from data/products.json — do not hand-edit between these markers) -->";
const END = "<!-- PRODUCTS:END -->";

function main() {
  const data = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  const expected = renderBands(data).trim();

  const html = readFileSync(HTML_PATH, "utf8");
  const startIdx = html.indexOf(START);
  const endIdx = html.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    console.error("MISMATCH: could not find PRODUCTS:START/END markers in portfolio.html");
    process.exit(1);
  }
  const actual = html.slice(startIdx + START.length, endIdx).trim();

  if (actual !== expected) {
    console.error("MISMATCH: portfolio.html has drifted from data/products.json.");
    console.error("Run `node scripts/build_portfolio.mjs` and commit the result.");
    console.error("--- expected (from data/products.json) ---");
    console.error(expected);
    console.error("--- actual (currently in portfolio.html) ---");
    console.error(actual);
    process.exit(1);
  }

  console.log(`OK: portfolio.html product cards match data/products.json (${data.products.length} records, ${expected.length} chars generated).`);
}

main();
